#!/usr/bin/env bash
#
# ASUS Zenbook Pro Duo 15 OLED (UX582ZW) - Linux internal speaker fix
# https://github.com/CodingButter/asus-ux582zw-speaker-fix
#
# LIMINE VARIANT
#
# Enables the two Cirrus Logic CS35L41 smart amplifiers that ASUS ships
# without ACPI _DSD configuration, by (1) forcing the legacy HDA audio
# driver and (2) injecting the missing _DSD via an SSDT ACPI override
# loaded from the initramfs.
#
# This version edits /boot/limine.conf (or /boot/limine/limine.conf)
# directly instead of GRUB_CMDLINE_LINUX_DEFAULT / GRUB_EARLY_INITRD_*:
#   - appends the kernel param to each entry's `cmdline:` line
#   - adds a second `module_path:` (+ `module_type: config`) line pointing
#     at the ACPI cpio, ahead of the main initramfs module
#
#   sudo ./install.sh              apply the fix (default)
#   sudo ./install.sh --check      run all checks, change nothing
#   sudo ./install.sh --uninstall  undo the fix
#   sudo ./install.sh --force      skip the exact-model guard (close siblings)
#   sudo ./install.sh --help
#
set -euo pipefail

# ---------------------------------------------------------------- constants ---
REPO_URL="https://github.com/CodingButter/asus-ux582zw-speaker-fix"
EXPECTED_BOARD="UX582ZW"
EXPECTED_SSID="1043:1a8f"          # ALC294 subsystem id on this machine
ACPI_HID="CSC3551"                 # Cirrus CS35L41 ACPI hardware id
KPARAM="snd_intel_dspcfg.dsp_driver=1"
CPIO_NAME="acpi-cs35l41-ux582zw.cpio"   # file in /boot
AML_MEMBER="cs35l41.aml"                # <=18 chars: kernel MAX_CPIO_FILE_NAME
BOOT_DIR="/boot"

# Candidate locations for limine.conf, in priority order.
LIMINE_CONF_CANDIDATES=(
  "/boot/limine.conf"
  "/boot/limine/limine.conf"
  "/boot/EFI/limine/limine.conf"
  "/boot/efi/limine.conf"
  "/boot/limine.cfg"          # older Limine versions used .cfg
)
LIMINE_CONF=""

# Marker text for a STANDALONE comment line (never appended to the end of
# a directive line - see the big warning in patch_limine_add() below for why).
TAG="asus-ux582zw-speaker-fix"

# BLAKE2B-512 hash (128 lowercase hex chars) of the installed cpio, computed
# in build_and_install_ssdt(). Empty until then.
CPIO_HASH=""

MODE="install"
FORCE=0
WORK=""

# ------------------------------------------------------------------- output ---
if [ -t 1 ]; then
  C_RED=$'\e[31m'; C_GRN=$'\e[32m'; C_YEL=$'\e[33m'; C_BLU=$'\e[34m'; C_BLD=$'\e[1m'; C_RST=$'\e[0m'
else
  C_RED=""; C_GRN=""; C_YEL=""; C_BLU=""; C_BLD=""; C_RST=""
fi
log()  { printf '%s==>%s %s\n'  "$C_BLU" "$C_RST" "$*"; }
ok()   { printf '  %s+%s %s\n'  "$C_GRN" "$C_RST" "$*"; }
warn() { printf '  %s!%s %s\n'  "$C_YEL" "$C_RST" "$*" >&2; }
die()  { printf '%sFAIL:%s %s\n' "$C_RED" "$C_RST" "$*" >&2; exit 1; }

cleanup() { [ -n "$WORK" ] && rm -rf "$WORK" 2>/dev/null || true; }
trap cleanup EXIT

usage() {
  cat <<EOF
${C_BLD}ASUS Zenbook Pro Duo UX582ZW - Linux speaker fix (Limine)${C_RST}

  sudo ./install.sh              apply the fix (default)
  sudo ./install.sh --check      run checks only, make no changes
  sudo ./install.sh --uninstall  undo the fix
  sudo ./install.sh --force      skip the exact-model guard (close siblings)
  sudo ./install.sh --help       show this help

$REPO_URL
EOF
  exit 0
}

banner() {
  printf '%s\n'   "${C_BLD}ASUS Zenbook Pro Duo UX582ZW - Linux speaker fix (Limine)${C_RST}"
  printf '%s\n\n' "$REPO_URL"
}

# -------------------------------------------------------------- limine find ---
find_limine_conf() {
  local c
  for c in "${LIMINE_CONF_CANDIDATES[@]}"; do
    if [ -f "$c" ]; then
      LIMINE_CONF="$c"
      return 0
    fi
  done
  return 1
}

# Detect whether limine.conf entries are auto-generated by
# limine-mkinitcpio / limine-entry-tool (Arch-style), in which case
# hand-editing gets clobbered on the next kernel update and we should
# instead drop a snippet those tools pick up, if supported, or warn loudly.
detect_generator() {
  if command -v limine-mkinitcpio >/dev/null 2>&1 || command -v limine-update >/dev/null 2>&1; then
    echo "limine-mkinitcpio"
  elif command -v limine-entry-tool >/dev/null 2>&1; then
    echo "limine-entry-tool"
  else
    echo "manual"
  fi
}

# ------------------------------------------------------------- conf editing ---
# We operate on limine.conf's block structure, e.g.:
#
#   /Arch Linux
#       protocol: linux
#       kernel_path: boot():/vmlinuz-linux
#       cmdline: root=UUID=... rw quiet
#       module_path: boot():/initramfs-linux.img
#       module_path: boot():/initramfs-linux-fallback.img
#
# Strategy (idempotent, per matching entry block):
#   1. cmdline: append $KPARAM if not already present on that line.
#   2. module_path: insert TWO new lines immediately before the first
#      existing module_path line in the block: a standalone tag comment,
#      then our own module_path pointing at the ACPI cpio (with a real
#      BLAKE2B hash appended, see below). Limine concatenates all
#      initramfs-classed modules for a given kernel in the order listed,
#      so ours must come first (ACPI override must be visible to the
#      kernel at the same "early" position GRUB's
#      GRUB_EARLY_INITRD_LINUX_CUSTOM would have given it).
#
# IMPORTANT - why the tag is its OWN line, never appended to a directive:
# Limine's config format treats '#' on a path line as the start of a
# mandatory BLAKE2B integrity hash (`boot():/kernel#<128-hex-char-hash>`),
# NOT as a trailing comment - comments are only recognised when '#' is the
# first non-blank character of an otherwise-empty line. An earlier version
# of this script appended "# <tag>" to the end of the module_path line,
# which Limine parsed as a malformed hash attempt and refused to boot with
# "PANIC: Blake2b hash must be 128 characters long". Never repeat that: any
# text placed after a bare '#' on a kernel_path/module_path/dtb_path line
# must be a real hash or nothing at all.
#
# To be robust even on systems where a Secure-Boot-enrolled config hash
# makes hashes on every path mandatory, we compute a real BLAKE2B-512 hash
# of the installed cpio (128 lowercase hex chars, via `b2sum`) and append
# it properly. This is harmless and verifies correctly whether or not this
# particular machine actually requires it.
#
# We use awk for block-aware, multi-entry editing rather than sed, since
# a limine.conf can (and often does) define several boot entries and we
# want the fix applied to every Linux entry, not just the first.

backup_limine_conf() {
  local ts bak
  ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo backup)"
  bak="${LIMINE_CONF}.bak.${ts}"
  cp -a "$LIMINE_CONF" "$bak"
  ok "backed up $LIMINE_CONF -> $bak"
}

# Returns 0 if the file changed (param/module added), 1 if already up to date.
patch_limine_add() {
  local tmp
  tmp="$(mktemp)"
  CPIO_NAME="$CPIO_NAME" CPIO_HASH="$CPIO_HASH" KPARAM="$KPARAM" TAG="$TAG" awk '
    BEGIN {
      cpio = ENVIRON["CPIO_NAME"]
      hash = ENVIRON["CPIO_HASH"]
      kparam = ENVIRON["KPARAM"]
      tag = ENVIRON["TAG"]
      in_linux_entry = 0
      inserted_module = 0
      module_uri = "boot():/" cpio
      if (length(hash) == 128) module_uri = module_uri "#" hash
      tag_line    = "    # " tag
      module_line = "    module_path: " module_uri
    }
    # Track whether we are inside a block whose protocol is linux/limine-friendly
    # (heuristic: any block containing a kernel_path or protocol: linux line).
    /^[^[:space:]]/ {
      # New top-level entry (starts a new "/Name" heading) -> reset per-entry state
      in_linux_entry = 0
      inserted_module = 0
    }
    /^[[:space:]]*protocol:[[:space:]]*linux/ { in_linux_entry = 1 }
    /^[[:space:]]*kernel_path:/ { in_linux_entry = 1 }

    # Skip a pre-existing tag comment line, and the module_path line right
    # after it, so re-running (or upgrading from an older cpio hash) is
    # idempotent instead of stacking duplicates.
    skip_next == 1 { skip_next = 0; next }
    $0 ~ ("^[[:space:]]*#[[:space:]]*" tag "[[:space:]]*$") { skip_next = 1; next }

    {
      line = $0
      if (in_linux_entry && line ~ /^[[:space:]]*cmdline:/) {
        if (index(line, kparam) == 0) {
          sub(/[[:space:]]*$/, "", line)
          line = line " " kparam
        }
      }
      if (in_linux_entry && !inserted_module && line ~ /^[[:space:]]*module_path:/) {
        print tag_line
        print module_line
        inserted_module = 1
      }
      print line
    }
  ' "$LIMINE_CONF" > "$tmp"

  if ! cmp -s "$tmp" "$LIMINE_CONF"; then
    mv "$tmp" "$LIMINE_CONF"
    return 0
  else
    rm -f "$tmp"
    return 1
  fi
}

patch_limine_remove() {
  local tmp
  tmp="$(mktemp)"
  KPARAM="$KPARAM" TAG="$TAG" awk '
    BEGIN { kparam = ENVIRON["KPARAM"]; tag = ENVIRON["TAG"] }
    # Drop our tag comment line AND the module_path line immediately after it.
    skip_next == 1 { skip_next = 0; next }
    $0 ~ ("^[[:space:]]*#[[:space:]]*" tag "[[:space:]]*$") { skip_next = 1; next }
    {
      line = $0
      if (line ~ /^[[:space:]]*cmdline:/) {
        # Remove " KPARAM" (with any surrounding spacing) from the cmdline value.
        gsub(" " kparam, "", line)
        gsub(kparam, "", line)
        gsub(/[[:space:]]+$/, "", line)
      }
      print line
    }
  ' "$LIMINE_CONF" > "$tmp"
  mv "$tmp" "$LIMINE_CONF"
}

verify_limine_conf() {
  local rc=0
  if grep -q "$KPARAM" "$LIMINE_CONF"; then
    ok "$LIMINE_CONF has $KPARAM on at least one cmdline"
  else
    warn "$KPARAM not found in $LIMINE_CONF"
    rc=1
  fi
  if grep -q "$CPIO_NAME" "$LIMINE_CONF"; then
    ok "$LIMINE_CONF references $CPIO_NAME as a module"
  else
    warn "$CPIO_NAME not referenced in $LIMINE_CONF"
    rc=1
  fi
  return $rc
}

# Limine reads limine.conf directly at boot - there is no "regenerate config"
# step the way update-grub/grub-mkconfig works, UNLESS the distro uses
# limine-mkinitcpio / limine-entry-tool to regenerate entries automatically
# on kernel/initramfs updates (common on Arch). In that case our hand-edits
# will be overwritten next kernel update, so warn clearly.
regen_or_warn() {
  local gen
  gen="$(detect_generator)"
  case "$gen" in
    limine-mkinitcpio|limine-entry-tool)
      warn "detected $gen managing limine.conf entries."
      printf '    Your edits were applied directly to %s and WILL work on next\n' "$LIMINE_CONF"
      printf '    boot, but %s may regenerate/overwrite this file on the next\n' "$gen"
      printf '    kernel or initramfs update, silently dropping the fix.\n'
      printf '    After any future kernel update, re-run:  sudo %s\n' "${0##*/}"
      printf '    (it is idempotent - safe to run again any time.)\n'
      ;;
    manual)
      ok "no auto-regenerating Limine entry tool detected - your edit is durable"
      ;;
  esac
  # Nothing to "run" for Limine itself - it reads limine.conf at boot time.
  # If limine is installed as a systemd-boot-style ESP deployment, make sure
  # the ESP copy is in sync (some setups keep limine.conf only on the ESP,
  # which is already where we edited it via LIMINE_CONF_CANDIDATES above).
}

# ------------------------------------------------------------------- checks ---
check_root() {
  if [ "$(id -u)" -ne 0 ]; then
    warn "must run as root"
    return 1
  fi
  return 0
}

check_os() {
  if ! command -v limine >/dev/null 2>&1 && ! find_limine_conf; then
    warn "Limine not detected (no 'limine' binary and no limine.conf found)."
    printf '    Looked in: %s\n' "${LIMINE_CONF_CANDIDATES[*]}"
    printf '    This script targets Limine systems. For GRUB, use the upstream\n'
    printf '    install.sh instead.\n'
    return 1
  fi
  if ! find_limine_conf; then
    warn "limine binary found but no limine.conf in the usual locations."
    printf '    Looked in: %s\n' "${LIMINE_CONF_CANDIDATES[*]}"
    printf '    If yours lives elsewhere, edit LIMINE_CONF_CANDIDATES at the top\n'
    printf '    of this script, or set LIMINE_CONF=/path/to/limine.conf and re-run.\n'
    return 1
  fi
  ok "Limine configuration present: $LIMINE_CONF"
  return 0
}

check_model() {
  local pn bn rc=0
  pn="$(cat /sys/class/dmi/id/product_name 2>/dev/null || true)"
  bn="$(cat /sys/class/dmi/id/board_name 2>/dev/null || true)"
  log "detected machine: ${pn:-unknown}  (board: ${bn:-unknown})"
  if printf '%s %s' "$pn" "$bn" | grep -q "$EXPECTED_BOARD"; then
    ok "model matches $EXPECTED_BOARD"
  elif [ "$FORCE" -eq 1 ]; then
    warn "model does not look like $EXPECTED_BOARD, but --force was given; continuing"
  else
    warn "this machine is not a $EXPECTED_BOARD (found: ${pn:-unknown})."
    printf '    If you have a very close CS35L41 sibling and know what you are doing,\n'
    printf '    re-run with --force. Otherwise this fix is not for your machine.\n'
    rc=1
  fi
  if ls -d /sys/bus/acpi/devices/${ACPI_HID}:* >/dev/null 2>&1; then
    ok "Cirrus CS35L41 amp device ($ACPI_HID) present"
  else
    warn "no $ACPI_HID (CS35L41) ACPI device found - this machine lacks the amps this fix targets."
    rc=1
  fi
  if grep -iq "${EXPECTED_SSID/:/}" /proc/asound/card*/codec#0 2>/dev/null \
     || lspci -nn 2>/dev/null | grep -iq "$EXPECTED_SSID"; then
    ok "audio subsystem id $EXPECTED_SSID detected"
  else
    warn "audio subsystem id $EXPECTED_SSID not detected (continuing)"
  fi
  return $rc
}

check_secureboot() {
  local sb="" ld="[none]"
  command -v mokutil >/dev/null 2>&1 && sb="$(mokutil --sb-state 2>/dev/null || true)"
  [ -r /sys/kernel/security/lockdown ] && ld="$(cat /sys/kernel/security/lockdown 2>/dev/null || true)"
  log "Secure Boot: ${sb:-unknown}   |   kernel lockdown: $ld"
  if printf '%s' "$sb" | grep -qi 'SecureBoot enabled' \
     || printf '%s' "$ld" | grep -qiE '\[(integrity|confidentiality)\]'; then
    warn "Secure Boot is ENABLED (kernel is locked down)."
    printf '    ACPI table overrides loaded from the initramfs are silently ignored\n'
    printf '    while Secure Boot is on, so the fix cannot take effect.\n'
    printf '    Disable Secure Boot first:\n'
    printf '      reboot -> tap F2 (or DEL) at the ASUS logo -> Security (or Boot) tab\n'
    printf '      -> Secure Boot Control -> Disabled -> save & exit -> re-run this script.\n'
    printf '    Note: some Limine setups also chainload via a signed shim; if you use\n'
    printf '    one, unsigned ACPI overrides are still blocked by kernel lockdown\n'
    printf '    exactly as under GRUB, regardless of Limine itself being unsigned.\n'
    return 1
  fi
  ok "Secure Boot off / lockdown none"
  return 0
}

run_checks() {
  local rc=0
  check_os         || rc=1
  check_model      || rc=1
  check_secureboot || rc=1
  return $rc
}

# ------------------------------------------------------------------ tooling ---
ensure_tools() {
  if ! command -v iasl >/dev/null 2>&1; then
    log "installing acpica-tools (provides iasl) ..."
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq || true
      DEBIAN_FRONTEND=noninteractive apt-get install -y acpica-tools >/dev/null \
        || die "failed to install acpica-tools"
    elif command -v pacman >/dev/null 2>&1; then
      pacman -Sy --noconfirm --needed acpica >/dev/null \
        || die "failed to install acpica (pacman)"
    elif command -v dnf >/dev/null 2>&1; then
      dnf install -y acpica-tools >/dev/null \
        || die "failed to install acpica-tools (dnf)"
    else
      die "iasl not found and no supported package manager detected. Install the ACPICA tools (package 'acpica-tools'/'acpica' or 'iasl') and re-run."
    fi
  fi
  command -v cpio >/dev/null 2>&1 || die "cpio not found (install the 'cpio' package)."
  ok "build tools present (iasl, cpio)"
}

# ------------------------------------------------------------- build + apply ---
build_and_install_ssdt() {
  WORK="$(mktemp -d)"
  local dsl="$WORK/${AML_MEMBER%.aml}.dsl"
  cat > "$dsl" <<'DSL'
DefinitionBlock ("", "SSDT", 2, "CBTR", "CS35L41", 0x00000001)
{
    External (_SB_.PC00.SPI1, DeviceObj)
    External (_SB_.PC00.SPI1.SPK1, DeviceObj)

    Scope (\_SB.PC00.SPI1.SPK1)
    {
        Name (_DSD, Package ()
        {
            ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301"),
            Package ()
            {
                Package () { "cirrus,dev-index", Package () { Zero, One } },
                Package () { "reset-gpios", Package () { ^SPK1, One, Zero, Zero, ^SPK1, One, Zero, Zero } },
                Package () { "spk-id-gpios", Package () { ^SPK1, 0x02, Zero, Zero, ^SPK1, 0x02, Zero, Zero } },
                Package () { "cirrus,speaker-position", Package () { Zero, One } },
                Package () { "cirrus,boost-type", Package () { One, One } },
                Package () { "cirrus,gpio1-func", Package () { One, One } },
                Package () { "cirrus,gpio2-func", Package () { 0x02, 0x02 } }
            }
        })
    }

    Scope (\_SB.PC00.SPI1)
    {
        Name (_DSD, Package ()
        {
            ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301"),
            Package ()
            {
                Package () { "cs-gpios", Package () { Zero, SPK1, Zero, Zero, Zero } }
            }
        })
    }
}
DSL

  log "compiling SSDT with iasl ..."
  ( cd "$WORK" && iasl -tc "$(basename "$dsl")" ) >/dev/null 2>&1 \
    || die "iasl failed to compile the SSDT"
  [ -f "$WORK/$AML_MEMBER" ] || die "iasl did not produce $AML_MEMBER"
  ok "SSDT compiled"

  log "packaging ACPI override into a cpio ..."
  mkdir -p "$WORK/cpioroot/kernel/firmware/acpi"
  cp "$WORK/$AML_MEMBER" "$WORK/cpioroot/kernel/firmware/acpi/$AML_MEMBER"
  ( cd "$WORK/cpioroot" && find kernel | cpio -H newc --create --quiet > "$WORK/$CPIO_NAME" )
  install -o root -g root -m 0644 "$WORK/$CPIO_NAME" "$BOOT_DIR/$CPIO_NAME"
  ok "installed $BOOT_DIR/$CPIO_NAME"

  # Compute the BLAKE2B-512 hash of the exact bytes now on disk (128 lowercase
  # hex chars). Limine requires this exact format for a path's "#<hash>"
  # suffix; on Secure-Boot-enrolled setups it's mandatory on every path, and
  # even where it isn't, attaching a correct one is harmless and adds
  # tamper-evidence for free. See the big comment above patch_limine_add().
  if command -v b2sum >/dev/null 2>&1; then
    CPIO_HASH="$(b2sum "$BOOT_DIR/$CPIO_NAME" | awk '{print $1}')"
    if [ "${#CPIO_HASH}" -eq 128 ]; then
      ok "computed module hash (blake2b-512, 128 hex chars)"
    else
      warn "b2sum produced an unexpected hash length (${#CPIO_HASH} chars) - continuing without a hash"
      CPIO_HASH=""
    fi
  else
    warn "b2sum not found - continuing without a module hash (fine unless your config enrolls Secure Boot hashing)"
    CPIO_HASH=""
  fi
}

# -------------------------------------------------------------------- modes ---
do_install() {
  banner
  run_checks || die "pre-flight checks failed (see above). Nothing was changed."
  ensure_tools
  backup_limine_conf
  build_and_install_ssdt

  if patch_limine_add; then
    ok "patched $LIMINE_CONF (kernel param + module_path)"
  else
    ok "$LIMINE_CONF already up to date - nothing to change"
  fi

  echo
  if verify_limine_conf; then
    printf '%s%s Fix applied. %s\n' "$C_GRN" "$C_BLD" "$C_RST"
  else
    warn "applied, but verification found problems - review $LIMINE_CONF before rebooting."
  fi
  regen_or_warn
  cat <<EOF

${C_BLD}Next step: REBOOT.${C_RST}
After rebooting, test the speakers:

    speaker-test -c2 -twav -l1          # Ctrl+C to stop
    wpctl status                        # (or Settings -> Sound) should list a Speaker

Confirm the amplifiers powered on:

    sudo dmesg | grep -i cs35l41
      expect:  "Firmware Loaded - Type: spk-prot"   (not "Platform not supported")

If it doesn't boot as expected, edit $LIMINE_CONF and confirm the
module_path for $CPIO_NAME is listed BEFORE your main initramfs
module_path line in each entry - Limine concatenates initramfs-class
modules in the order given, and the ACPI override must be visible early.

Undo everything:   sudo ${0##*/} --uninstall
EOF
}

do_uninstall() {
  banner
  check_root || die "must run as root"
  find_limine_conf || die "could not find limine.conf (looked in: ${LIMINE_CONF_CANDIDATES[*]})"
  backup_limine_conf
  patch_limine_remove
  ok "reverted $LIMINE_CONF"
  rm -f "$BOOT_DIR/$CPIO_NAME"
  rm -f "$BOOT_DIR"/acpi_ux582zw.cpio 2>/dev/null || true   # legacy ad-hoc name
  ok "removed the ACPI cpio from /boot"
  regen_or_warn
  cat <<EOF

${C_BLD}Uninstalled.${C_RST} Reboot to return to the stock audio driver.
Note: this does not re-enable Secure Boot - do that in your UEFI/BIOS if you want it back.
EOF
}

do_check() {
  banner
  if run_checks; then
    ok "all checks passed - this machine is ready for the fix"
  else
    warn "one or more checks failed (see above)"
  fi
  echo
  log "current install state:"
  [ -f "$BOOT_DIR/$CPIO_NAME" ] && ok "cpio installed: $BOOT_DIR/$CPIO_NAME" || warn "cpio not installed"
  if find_limine_conf; then
    grep -q "$KPARAM"    "$LIMINE_CONF" 2>/dev/null && ok "$KPARAM present in $LIMINE_CONF"    || warn "$KPARAM not set in $LIMINE_CONF"
    grep -q "$CPIO_NAME" "$LIMINE_CONF" 2>/dev/null && ok "$CPIO_NAME referenced in $LIMINE_CONF" || warn "$CPIO_NAME not referenced in $LIMINE_CONF"
  else
    warn "limine.conf not found - cannot report cmdline/module state"
  fi
  echo
  log "no changes were made (--check)."
}

# --------------------------------------------------------------------- main ---
for a in "${@:-}"; do
  case "$a" in
    --uninstall) MODE="uninstall" ;;
    --check)     MODE="check" ;;
    --force)     FORCE=1 ;;
    -h|--help)   usage ;;
    "")          ;;
    *)           die "unknown argument: $a  (try --help)" ;;
  esac
done

# Re-exec with sudo for install/uninstall when possible.
if [ "$MODE" != "check" ] && [ "$(id -u)" -ne 0 ]; then
  if [ -f "${BASH_SOURCE[0]:-}" ]; then
    exec sudo -- "$0" "$@"
  fi
  die "please run as root:  sudo $0 $*    (or pipe the one-liner through 'sudo bash')"
fi

case "$MODE" in
  install)   do_install ;;
  uninstall) do_uninstall ;;
  check)     do_check ;;
esac
